### ISSUE TITLE
Modal onShown not working

### ISSUE THREAD

**Issue by pm100** [havit/Havit.Blazor#60] opened 2022-01-11 06:27 UTC
Just upgraded to 2.0 cos i saw this new feature. I suspect I have a timing issue (Modal is popluated by background stuff once its shown) and this looked like a solution, ie wait till modal is fully shown. But the callback is not executed (the modal shows and works fine, apart from my timing issue)

```
<HxModal @ref="_modal" Title="Listening" OnClosed="Closed" OnShown="Shown">
	<BodyTemplate>
		<div>
			I heard: @_notes
		</div>
		<HxBadge Color="ThemeColor.Success">Yup</HxBadge>
		<HxProgress>
    <HxProgressBar Label="" MaxValue=@Max Value=@Time />
</HxProgress>

	</BodyTemplate>
	<FooterTemplate>
		<HxButton Text="Close" OnClick="HandleClose" Color="ThemeColor.Primary" />
	</FooterTemplate>
</HxModal>
```

then 
```
.......
	public void Shown() {
		Util.Log($"shown {_listening}");
		
	}
.....
```
the shown code is never called

**Comment by hakenr** [comment] 2022-01-11 08:16
Hi @pm100,
unfortunately, I was not able to reproduce your issue.

If I create a simple repro (add `OnShown` to the first `HxModal` demo), the `OnShown` message gets logged to console:
```razor
<HxButton OnClick="HandleShowClick" Color="ThemeColor.Primary">Show modal</HxButton>

<HxModal @ref="myModal" Title="Modal title" OnShown="@(() => Console.WriteLine("OnShown"))">
	<BodyTemplate>
		Modal body
	</BodyTemplate>
	<FooterTemplate>
		<HxButton Text="Close" OnClick="HandleHideClick" Color="ThemeColor.Primary" />
	</FooterTemplate>
</HxModal>

@code
{
	private HxModal myModal;

	private async Task HandleShowClick()
	{
		await myModal.ShowAsync();
	}

	private async Task HandleHideClick()
	{
		await myModal.HideAsync();
	}

}
```

Please doublecheck your code and if you still experience this issue, please provide more detailed steps to reproduce.
Thank you.

**Comment by hakenr** [comment] 2022-01-11 23:24
Oops, this has to be copy&paste mistake in the doc, will fix.

**Comment by hakenr** [comment] 2022-01-11 23:30
Fixed with 9c06bd3ad17639af952cd7d8eb29327d6d3bc44b

**Closed by hakenr** 2022-01-11 23:30 UTC
Labels: documentation, unable to reproduce

**Comment by pm100** [comment] 2022-01-12 00:42
question, how come the Modal isnt fully shown by the time the awaited ShowAsync is completed? The natural assumption is that if I do `await modal.ShowAsync()` then when control returns to me the Modal is ready to go. I needed to actually wait till OnShow callback is called (otherwise I got timing errors that were hard to track down) - the doc needs to explain what is and isnt ready when `await modal.ShowAsync()` completes

**Comment by hakenr** [comment] 2022-01-15 16:08
@pm100, this is based on fact that the Bootstrap's modal component has a "transition" (animation) when being shown. The ShowAsync() method triggers the action, but it returns before the transition is completed. That's why there is the OnShown event. Will try to make this more obvious in the doc.
