### ISSUE TITLE
[HxInputBase] - Make overridable members available outside of the package

### ISSUE THREAD

**Issue by TPIvan** [havit/Havit.Blazor#440] opened 2022-12-09 14:19 UTC
`HxInputBase` has methods like `CoreInputCssClass `or `IsValueInvalid` which are widely used in form controls and they are marked `private protected` and so they cannot be used outside the assembly. I think that they should be marked `internal protected` to enable creation of components in a project using _Havit.Blazor_ package.

There is probably a workaround - overriding `GetInputCssClassToRender` and recreating `IsValueInvalid` but it at least doesn't look well.

**Comment by hakenr** [comment] 2022-12-12 12:24
Hi @TPIvan,
thank you for your request.
Just to be sure, can you please describe the scenario where you want to override those properties?

We might change the access modifier for those properties, but I need to see the real scenario for that.
(We're a bit cautious about these properties right now because we have some design changes planned which might involve further changes in internal structure: #204)

**Comment by TPIvan** [comment] 2022-12-12 13:07
I need to create Select (drop-down list) with added features (filtering and grouping). As a first attempt I copied `HxMultiSelect `source code to my testing project.  Because it overrides `CoreInputCssClass `I was not able to to compile the project. Without overriding the resulting element is not styled properly. I found that the function is used in  `GetInputCssClassToRender`  and after copying and modification the function from the parent (`HxInputBase`) the compilation was successful.

My understanding is that when I want to create a new form element it is better to derive from `HxInputBase` to preserve consistency with other form elements in the library.  `CoreInputCssClass` seems to me as a key for setting CSS class of the base element of a form component.

I noticed #204 before starting the issue but I considered it to be completed with access modifiers deficiency.

**Comment by surgicalcoder** [comment] 2022-12-23 00:20
I'd like to chime in on HxInputBase - BuildRenderTree is sealed, so I can't inherit from HxCheckbox.

My use case for this is I want to create custom components with some defaults and some logic (automatically calculate Label from the ValueExpression) - but I can't because:

Error CS0239 : 'RowInputBoolean2.BuildRenderTree(RenderTreeBuilder)': cannot override inherited member 'HxInputBase<bool>.BuildRenderTree(RenderTreeBuilder)' because it is sealed

My personal opinion - it feels a bit unnecessary to have loads of sealed members everywhere, especially given this is an open source project - I can easily fork this, unseal things and publish my own, however I think the wider community would benefit from being able to do more with this library, I don't see what sealing things adds, apart from making it slightly more difficult to achieve what you want.

**Comment by hakenr** [comment] 2022-12-23 23:58
Hi @surgicalcoder,

> I'd like to chime in on HxInputBase - BuildRenderTree is sealed, so I can't inherit from HxCheckbox.

The `BuildRenderTree` method is sealed intentionally as it forces specific behavior and structure of the input-components. The rendering itself is delegated to `HxFormValueRenderer` (and `HxFormValueComponentRenderer`) and to influence the rendering you should override some of the new methods instead:
* `BuildRenderInput`
* `BuildRenderValidationMessage`
* `RenderChipGenerator`
* ...

See implementation of our input-components to get the inspiration on how to arrange the rendering.

**Comment by hakenr** [comment] 2023-08-14 14:50
@TPIvan Unfortunately not, the #204 is still on our roadmap as intended approach.

**Comment by hakenr** [comment] 2024-01-02 16:06
I'm closing this issue since it doesn't offer any new implementation ideas beyond those in #204, which is already on our roadmap.

**Closed by hakenr** 2024-01-02 16:06 UTC

**Comment by TPIvan** [comment] 2024-01-03 12:27
#204 seems to be only address the problem of combining `CSS `classes but this issue includes also `IsValueInvalid` which is also `private protected`.

**Comment by hakenr** [comment] 2024-01-03 12:56
`IsValueInvalid()` does not carry any additional logic, it is just a "readability helper" for our own implementations which we do not want to "promise, it will be there forever".
```csharp
private protected bool IsValueInvalid() => EditContext.GetValidationMessages(FieldIdentifier).Any();
```
(`EditContext` is defined in `InputBase` as `protected`.

**Comment by TPIvan** [comment] 2024-01-05 10:03
I understand your reasoning for making `IsValueInvalid()` a `private protected` method, but it makes it harder to reuse and customize your components. If someone wants to copy some component and modify it, they would have to rewrite or duplicate the logic of `IsValueInvalid()`. 

Of course, it is your library and you can design it as you wish.
