### ISSUE TITLE
[HxInputDate] dark mode broken in Edge

### ISSUE THREAD

**Issue by resignationinfinite** [havit/Havit.Blazor#750] opened 2024-02-05 19:31 UTC
Only happens in Edge so far as I can tell.

Video:
https://github.com/havit/Havit.Blazor/assets/10275357/3640c98f-ec38-42e2-bade-13f485a34190

**Comment by hakenr** [comment] 2024-02-13 09:23
@crdo I'm able to reproduce the reported issue.
The issue disappears when I force `:hover` on the `select` element:
![image](https://github.com/havit/Havit.Blazor/assets/12828888/414fbfda-66d3-44ad-a9ea-f07ccd102210)

**Comment by hakenr** [comment] 2024-02-13 09:25
![2024-02-13_10-24-36](https://github.com/havit/Havit.Blazor/assets/12828888/2e9c0e6c-60b1-4c90-9db3-88c4a6debc8b)

**Comment by crdo** [comment] 2024-04-11 08:58
@hakenr to me this feels more like a browser bug rather than issue in our library.

**Comment by crdo** [comment] 2024-07-15 19:39
Although I still believe this is a browser bug and I cannot reproduce it as it works on all browsers across macOS I rewrote the CSS to get rid of that silly :not(:hover) selector.
@hakenr please let me know if it helped or make a pre-release so @hrocha1 or @resignationinfinite can test it.

**Comment by hrocha1** [comment] 2024-07-15 19:47
Might be an issue with some Windows native UI elements. I haven't been able to reproduce it on macOS or Linux either.

**Comment by hakenr** [comment] 2024-07-16 07:01
release `4.6.11-pre2`, make sure you clear your browser cache (previous version of CSS bundle)

**Comment by crdo** [comment] 2024-07-16 14:22
After a quick testing with @alexax578 I think it is fixed.

**Comment by hrocha1** [comment] 2024-07-16 16:16
@crdo Can confirm it works on my side, thanks 👍

**Comment by crdo** [comment] 2024-07-17 06:54
Closing as fixed. 
Will be part of the `4.6.11` release.

**Closed by crdo** 2024-07-17 06:54 UTC
Labels: bug
