### ISSUE TITLE
[HxTooltip] - Tooltip is sometimes shown at wrong position on the page

### ISSUE THREAD

**Issue by pavmal12** [havit/Havit.Blazor#404] opened 2022-10-13 08:31 UTC
In some scenarios when I move mouse over element with tooltip, then move over and again move back to element, the tooltip is shown at the bottom of the page. 

![image](https://user-images.githubusercontent.com/110027149/195544891-14cb1fa9-a8e4-4573-828f-03c68033b1d4.png)

**Comment by alexax578** [comment] 2022-10-13 14:04
The mentioned behavior probably occurs when I quickly move move away from the element with tooltip and then back over before the tooltip has finished disappearing.

**Comment by hakenr** [comment] 2022-10-21 10:41
I'm unable to reproduce.
Can you please tak a look, @crdo?

**Comment by crdo** [comment] 2022-11-01 11:11
It is a Bootstrap issue. If you hover the tooltip while it is being hidden and the hide animation is still in progress, it breaks.
https://github.com/twbs/bootstrap/issues/36875

**Comment by hakenr** [comment] 2024-01-02 16:09
The issue seems to be fixed in Bootstrap 5.2.3.

**Closed by hakenr** 2024-01-02 16:09 UTC
Labels: bug, waiting-bootstrap
