### ISSUE TITLE
HxGrid unable to set 100% height

### ISSUE THREAD

**Issue by franky1017** [havit/Havit.Blazor#831] opened 2024-06-15 13:55 UTC
I was trying to make the grid component to 100% height by setting the "TableContainerCssClass" property. That did not work. The reason was there was a outside div for the table called "hx-progress-overlay". Once I override that class to height 100% it works fine.

**Comment by crdo** [comment] 2024-06-21 05:55
This is intended behaviour. We need to wrap the `TableContainer` with another `div` to be able to position the `HxProgressIndicator` over the table.
There was an attempt to merge these two `divs` but w/o success so far. 
It is tracked at #465.
Closing as duplicate.

**Closed** 2024-06-21 05:55 UTC

**Comment by hakenr** [comment] 2024-06-21 07:34
Use HXGrid.CssClass to set class for the most outer element.

**Comment by franky1017** [comment] 2024-06-21 10:34
> Use HXGrid.CssClass to set class for the most outer element.

Maybe I am missing something, the HxGrid component has no CssClass property. Either "TableContainerCssClass" or "TableCssClass".

**Comment by crdo** [comment] 2024-06-21 10:37
@hakenr @franky1017 the most outer element that comes with `HxProgressIndicator` is not accessible with any CSS parameter.

**Comment by franky1017** [comment] 2024-06-21 10:39
> @hakenr @franky1017 the most outer element that comes with `HxProgressIndicator` is not accessible with any CSS parameter.

I understand that and that's the issue. Because of this outer div, when I try to set the height for the grid, it does not work because this outer div is controller the height for the grid. I had to add my own css class to set the progress indicator div's height to make it work.

**Comment by hakenr** [comment] 2024-06-24 11:41
Right now, we are testing a `HxGrid` adjustment where we squash the two outer `div`s into a single one (3b04c96130034888115f85b76cf95394fa5032fd).
I will publish a pre-release version for testing soon (v 4.6.10-pre1).
