### ISSUE TITLE
[HxGrid] When using Multiselect & Pagination, the selection is removed when navigating to other page.

### ISSUE THREAD

**Issue by jim-craane** [havit/Havit.Blazor#576] opened 2023-08-11 08:17 UTC
When using HXGrid with Multiselect & Pagination, the selection is removed when navigating to other page.
Is this by design? Because it's very annoying. 

Steps to reproduce:
1. Go to https://havit.blazor.eu/components/HxGrid#multiselect
2. Select some rows on first page
3. Navigate to second page
4. Navigate back to first page

Expected behaviour:
Paging/Filtering/Sorting doesn't have any influence on selected items.

**Comment by hakenr** [comment] 2023-08-14 14:53
This is currently intended behavior as the multi-selection is usually being used for mass-operations and we want the user to see affected items.

What is the scenario you are trying to solve and how do you expect the component to behave? Can you provide us with some links to other component implementations where this behaves as you expect?

**Comment by jim-craane** [comment] 2023-08-21 07:55
Examples of datagrid multiselect with pagination in other blazor UI frameworks:
https://blazor.radzen.com/datagrid-multiple-selection
https://antblazor.com/en-US/components/table
https://mudblazor.com/components/datagrid#advanced-data-grid

I expect that that the datagrid just stores the selected items also after navigating to the next page. People are responsible for them self's to select or not. The only thing with the 'select all' checkbox is that you can't select all on all pages with using server side sorting/filtering. But a lot of these datagrids are also used with just client side data.

So maybe make the row selection behavior configurable?

**Comment by hakenr** [comment] 2023-08-21 14:16
Both Radzen and MudBlazor maintain selection when paging, but it seems Ant loses the selection. Currently, we've chosen not to preserve the selection. However, this could change if there's increased feedback or interest from our users. As of now, it's not on our priority list.

**Comment by hakenr** [comment] 2024-10-15 07:54
Current outlook: We will make this configurable in the near future.

**Comment by benholtsclaw** [comment] 2024-11-25 03:06
I feel like I could come up with a lot of hypothetical scenarios where maintaining selection from page to page or through filtering and sorting would be beneficial, but here's how I've used it previously with another library.

I've have an application that manages the lottery and application process for our school. The lottery process is on the backend and is administered by school employees. We have multiple lotteries that represent different criteria (usually based on grade). When the school administrator is presented with the page to create a new lottery, she also sees a datagrid containing all applicants who haven't yet been assigned to a lottery. She provides the details of the lottery and selects the students who should be assigned to it. Same goes for the edit screen. When I load the details of the lottery to be edited, I can bind to the SelectedItems property those students who are already assigned to that lottery. Additional students can be added or students can be removed by just checking and unchecking datagrid rows.

Maybe I'm just having tunnel vision because this is how I previously designed the UI using another component library, but I'm at a loss for how I would even provide this functionality without a property like SelectedItems.

**Comment by hakenr** [comment] 2024-11-25 09:25
Let's add a new `PreserveSelection` parameter (along with `GridSettings.PreserveSelection` to support [Defaults & Settings](https://havit.blazor.eu/concepts/defaults-and-settings)).
The default value will be `false` to prevent breaking changes.

**Comment by hakenr** [comment] 2024-11-25 14:52
`v4.7.2-pre02`

**Closed by hakenr** 2024-11-25 14:52 UTC
Labels: enhancement, as designed, Premium

**Comment by benholtsclaw** [comment] 2024-11-27 04:21
What I'm seeing is that the collection is preserved, but the ui doesn't stay in sync with the collection. If I select some items from page 1, then move to another page, the items aren't still selected when I come back.

https://github.com/user-attachments/assets/4885bac7-71ed-4507-a937-ee5af6dde212

**Comment by hakenr** [comment] 2024-11-27 08:31
@benholtsclaw This issue usually happens when data identity isn't handled correctly. If you're using a `class` for your items (`TItem`), the default behavior of `item1.Equals(item2)` relies on reference equality (only identical instances are treated as equal).  

To fix this, you can:  
- **Override `bool Equals()`** to specify how equality should work (e.g., compare items by their data, such as `Id` in typical scenarios).  
- **Use a `record`** for your items, where the compiler automatically generates equality logic that compares all properties.  

(Most likely, in your case, the `SelectedDataItems` collection contains instances from an earlier `DataProvider` roundtrip. When you return to the same grid page, the `DataProvider` provides new instances for the same rows, and since `item.Equals(item)` returns `false` for these, they don't appear selected in the UI.)
