### ISSUE TITLE
[HxInputDate] throws InvalidOperationException: JavaScript interop calls cannot be issued

### ISSUE THREAD

**Issue by resignationinfinite** [havit/Havit.Blazor#631] opened 2023-10-17 22:04 UTC
Occurs only on initial page load. This seems to be an issue only in recent Havit Blazor and/or ASP.NET Core point releases (I did not change any relevant code on my end since the error started to appear).

```
ERROR|Microsoft.AspNetCore.Server.Kestrel|Connection id "0HMUFBH6R56U8", Request id "0HMUFBH6R56U8:00000001": An unhandled exception was thrown by the application. System.AggregateException: Exceptions were encountered while disposing components. (JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.) (JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.)
 ---> System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.EnsureJsModuleAsync()
   at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.HideAsync()
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.CloseDropdownAsync()
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsyncCore()
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.EnsureJsModuleAsync()
   at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.HideAsync()
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.CloseDropdownAsync()
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsyncCore()
   at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()<---
```

**Comment by hakenr** [comment] 2023-10-17 23:19
We did not change anything related on our side and this seems to be caused by a change in ASP.NET Core implementation. Did you upgrade to .NET 8:

It seems you are hitting the scenario where the `Dispose` gets called before the `OnAfterRender` method finished.
https://github.com/havit/Havit.Blazor/blob/c4479f058ceafe646b3fe901b080c9a5a8d0fd5d/Havit.Blazor.Components.Web.Bootstrap/Forms/Internal/HxInputDateInternal.razor.cs#L234-L249
This should have been covered by the `catch (JSDisconnectedException)` in the `DisposeAsyncCore()` implementation but it seems there is an `InvalidOperationException` being thrown in some scenarios now.

I will investigate the circumstances further to better prevent such symptoms.
Are you able to create a simple repo (project) which reproduces the error?

**Comment by hakenr** [comment] 2023-10-17 23:22
Note to my self: If confirmed, this has to be resolved in all the `DisposeAsyncCore` implementations calling JS, not just `HxInputDateInternal`. One of possible solutions might be to use a `protected bool firstRenderFinished` which gets set in `override OnAfterRenderAsync()` and tested in the `DisposeAsyncCore`.

**Comment by hakenr** [comment] 2023-10-19 15:54
Let me give it a try, I'll let you know in a while.

**Comment by hakenr** [comment] 2023-10-19 16:25
In the end, I was able to reproduce the issue:
- `BlazorAppTest`: `/HxInputDate_Issue631_Test`
- hit `F5`
- see _ASP.NET Core Web Server_ console output (or any other way to see server exceptions not propagated to the client)

```
fail: Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer[2]
﻿      Connection ID "18086456125800054801", Request ID "40000012-0005-fb00-b63f-84710c7967bb": An unhandled exception was thrown by the application.
﻿      System.AggregateException: Exceptions were encountered while disposing components. (JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.) (JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.)
﻿       ---> System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
﻿         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
﻿         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
﻿         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
﻿         at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.EnsureJsModuleAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Dropdowns\HxDropdownToggleElement.cs:line 186
﻿         at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.HideAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Dropdowns\HxDropdownToggleElement.cs:line 157
﻿         at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.CloseDropdownAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Forms\Internal\HxInputDateInternal.razor.cs:line 154
﻿         at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsyncCore() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Forms\Internal\HxInputDateInternal.razor.cs:line 238
﻿         at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Forms\Internal\HxInputDateInternal.razor.cs:line 225
﻿         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
﻿         --- End of inner exception stack trace ---
﻿         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
﻿      --- End of stack trace from previous location ---
﻿         at Microsoft.AspNetCore.Components.RenderTree.Renderer.DisposeAsync()
﻿         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.<DisposeAsync>g__Await|22_0(Int32 i, ValueTask vt, List`1 toDispose)
﻿         at Microsoft.AspNetCore.Http.Features.RequestServicesFeature.<DisposeAsync>g__Awaited|9_0(RequestServicesFeature servicesFeature, ValueTask vt)
﻿         at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContext.FireOnCompleted()
﻿       ---> (Inner Exception #1) System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.
﻿         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
﻿         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
﻿         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
﻿         at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.EnsureJsModuleAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Dropdowns\HxDropdownToggleElement.cs:line 186
﻿         at Havit.Blazor.Components.Web.Bootstrap.HxDropdownToggleElement.HideAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Dropdowns\HxDropdownToggleElement.cs:line 157
﻿         at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.CloseDropdownAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Forms\Internal\HxInputDateInternal.razor.cs:line 154
﻿         at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsyncCore() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Forms\Internal\HxInputDateInternal.razor.cs:line 238
﻿         at Havit.Blazor.Components.Web.Bootstrap.Internal.HxInputDateInternal`1.DisposeAsync() in D:\Development\002.HFW-Havit.Blazor\Havit.Blazor.Components.Web.Bootstrap\Forms\Internal\HxInputDateInternal.razor.cs:line 225
﻿         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass74_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()<---
```

**Closed** 2023-10-19 16:57 UTC
Labels: bug
