### ISSUE TITLE
[HxInputDate] - can not select date after manually deleting it

### ISSUE THREAD

**Issue by pavmal12** [havit/Havit.Blazor#266] opened 2022-07-26 10:01 UTC
If i will remove manually date from input while datepicker is open and immediately after removing will select new date, the date will not be selected and calendar will be closed.

**Comment by hakenr** [comment] 2022-07-26 10:47
Successfully reproduced.

**Comment by hakenr** [comment] 2022-07-29 08:15
Whenever the input (text) value changes, the click to calendar is not applied (onchange wins).

**Comment by Harvey1214** [comment] 2022-08-11 11:08
@hakenr I attempted to solve the issue by removing the call to close the dropdown menu `OnChange` (on valid change). However, that introduces another issue - when an incorrect date is manually entered - the dropdown is automatically closed because of [this issue](https://github.com/havit/Havit.Blazor/issues/294) (which is probably correct and doesn't impact this issue) but then when the user opens the dropdown menu and manually (by typing) changes the date to a valid one, the dropdown menu can't be closed by clicking outside of it - the OK button oslt has to be clicked in order to close the dropdown menu, so removing the call that's closing the dropdown menu on valid change is not a viable solution.

If you have an idea for how to solve this issue, please let me know, thank you and have a great day 😀

**Comment by jirikanda** [comment] 2022-08-16 15:53
Implementation notes: 
* We do not close the calendar when the value is changed anymore.
* The calendar is closed when the input is leaved "by bootstrap". The calendar in HxInputDate is no more accessible by the tab key.
* It supports the use case to seamlessly navigate through the form using keyboard.

**Comment by jirikanda** [comment] 2022-08-16 16:03
Done, @hakenr.
I suggest to remove the "OK" buttons from HxInputDate and HxInputDateRange calendars. I consider them useless now. @hakenr says it is on you, @crdo to decide.

**Comment by hakenr** [comment] 2022-08-17 07:14
Extracted the OK-button suggestion to separate issue. Closing this issue.

**Closed by hakenr** 2022-08-17 07:14 UTC
Labels: bug
